// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"
)

type Chat struct {
	ChatID         string       `json:"chatId"`
	ClientsIPsList []string     `json:"clientsIPsList"`
	LatestMessage  *TextMessage `json:"latestMessage"`
	ChatAvatar     *string      `json:"chatAvatar"`
	ClientWriting  *string      `json:"clientWriting"`
}

type TextMessage struct {
	ChatID    string    `json:"chatId"`
	User      string    `json:"user"`
	TimeStamp time.Time `json:"timeStamp"`
	Text      string    `json:"text"`
}
