// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

import (
	"time"
)

type Chat struct {
	ChatID         string   `json:"chatId"`
	ClientsIPsList []string `json:"clientsIPsList"`
}

type TextMessage struct {
	ChatID    string    `json:"chatId"`
	User      string    `json:"user"`
	TimeStamp time.Time `json:"timeStamp"`
	Text      string    `json:"text"`
}
