// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arxen.proto

package arxen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_14263d62e1c6ef9e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type MessageDeliveryStatusResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageDeliveryStatusResponse) Reset()         { *m = MessageDeliveryStatusResponse{} }
func (m *MessageDeliveryStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MessageDeliveryStatusResponse) ProtoMessage()    {}
func (*MessageDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14263d62e1c6ef9e, []int{1}
}

func (m *MessageDeliveryStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageDeliveryStatusResponse.Unmarshal(m, b)
}
func (m *MessageDeliveryStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageDeliveryStatusResponse.Marshal(b, m, deterministic)
}
func (m *MessageDeliveryStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageDeliveryStatusResponse.Merge(m, src)
}
func (m *MessageDeliveryStatusResponse) XXX_Size() int {
	return xxx_messageInfo_MessageDeliveryStatusResponse.Size(m)
}
func (m *MessageDeliveryStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageDeliveryStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageDeliveryStatusResponse proto.InternalMessageInfo

func (m *MessageDeliveryStatusResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Message struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ChatID               string               `protobuf:"bytes,2,opt,name=ChatID,proto3" json:"ChatID,omitempty"`
	MessageBody          string               `protobuf:"bytes,3,opt,name=MessageBody,proto3" json:"MessageBody,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_14263d62e1c6ef9e, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *Message) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*MessageDeliveryStatusResponse)(nil), "MessageDeliveryStatusResponse")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() {
	proto.RegisterFile("arxen.proto", fileDescriptor_14263d62e1c6ef9e)
}

var fileDescriptor_14263d62e1c6ef9e = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0xaa, 0x48,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x20,
	0x0a, 0x94, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0xcc, 0xb9, 0x64, 0x7d, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x5d, 0x52, 0x73, 0x32, 0xcb, 0x52, 0x8b, 0x2a, 0x83, 0x4b, 0x12,
	0x4b, 0x4a, 0x8b, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x20,
	0x22, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x50, 0x9e, 0xd2, 0x44, 0x46, 0x2e, 0x76, 0xa8,
	0x4e, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0xb0, 0x0a, 0xce, 0x20, 0x30, 0x1b, 0xa4,
	0xcf, 0x39, 0x23, 0xb1, 0xc4, 0xd3, 0x45, 0x82, 0x09, 0x2c, 0x0a, 0xe5, 0x09, 0x29, 0x70, 0x71,
	0x43, 0xb5, 0x39, 0xe5, 0xa7, 0x54, 0x4a, 0x30, 0x83, 0x25, 0x91, 0x85, 0x84, 0x2c, 0xb8, 0x38,
	0x43, 0x60, 0xce, 0x95, 0x60, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x78, 0x48, 0x0f,
	0xe6, 0x21, 0x3d, 0xb8, 0x8a, 0x20, 0x84, 0x62, 0xa3, 0x40, 0x2e, 0x11, 0x34, 0xcf, 0xb8, 0x96,
	0xa5, 0xe6, 0x95, 0x08, 0x59, 0x72, 0x71, 0x07, 0xa7, 0xe6, 0xa5, 0xc0, 0x9c, 0xcb, 0xa1, 0x07,
	0x65, 0x49, 0xc9, 0xe9, 0xe1, 0xf5, 0xbc, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x46, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0x7b, 0xe8, 0x64, 0x5f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessageDeliveryEventClient is the client API for MessageDeliveryEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageDeliveryEventClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageDeliveryStatusResponse, error)
}

type messageDeliveryEventClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageDeliveryEventClient(cc grpc.ClientConnInterface) MessageDeliveryEventClient {
	return &messageDeliveryEventClient{cc}
}

func (c *messageDeliveryEventClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageDeliveryStatusResponse, error) {
	out := new(MessageDeliveryStatusResponse)
	err := c.cc.Invoke(ctx, "/MessageDeliveryEvent/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageDeliveryEventServer is the server API for MessageDeliveryEvent service.
type MessageDeliveryEventServer interface {
	SendMessage(context.Context, *Message) (*MessageDeliveryStatusResponse, error)
}

// UnimplementedMessageDeliveryEventServer can be embedded to have forward compatible implementations.
type UnimplementedMessageDeliveryEventServer struct {
}

func (*UnimplementedMessageDeliveryEventServer) SendMessage(ctx context.Context, req *Message) (*MessageDeliveryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterMessageDeliveryEventServer(s *grpc.Server, srv MessageDeliveryEventServer) {
	s.RegisterService(&_MessageDeliveryEvent_serviceDesc, srv)
}

func _MessageDeliveryEvent_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageDeliveryEventServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageDeliveryEvent/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageDeliveryEventServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageDeliveryEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MessageDeliveryEvent",
	HandlerType: (*MessageDeliveryEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageDeliveryEvent_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arxen.proto",
}
